In [15]:
##This will install numpy package in for this notebook.
##pip install numpy

In [1]:
##import here to use it
import numpy as np
##checking the version
print(np.__version__)

x=np.array([11,1,2,3])
print(x)
#check the data type
print(x.dtype)
nlist=[5,9,23,87]
x_np=np.array(nlist,dtype=np.int8)
print(x_np)
x_np.dtype

2.5.1
[11  1  2  3]
int64
[ 5  9 23 87]


dtype('int8')

In [2]:
## multidimesnional list
m_list=[[1,2,3],[8,9,6],[11,32,90]]
m_list

[[1, 2, 3], [8, 9, 6], [11, 32, 90]]

In [3]:
## multidimesnional numpy array
np_m_list=np.array(m_list)
#np_m_list=np.array(m_list, dtype=np.int8) //passing data type
print("Data type: ",np_m_list.dtype)
np_m_list

Data type:  int64


array([[ 1,  2,  3],
       [ 8,  9,  6],
       [11, 32, 90]])

In [23]:
np_int1=np.arange(1,10) #start & stop
np_int1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np_int2=np.arange(1,10,2) #start, stop & step
np_int2

array([1, 3, 5, 7, 9])

In [30]:
#floating
np_int3=np.arange(0.1,1.3,0.09) #start, stop & step
np_int3


array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91, 1.  ,
       1.09, 1.18, 1.27])

In [4]:
#alternative
##The numpy.linspace() function generates an array of evenly spaced numbers over a specified mathematical interval
np_int4=np.linspace(0,10,5,retstep=True)
np_int4

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))

In [5]:
#Create a four items of zeros
np_0=np.zeros(4)
np_0

array([0., 0., 0., 0.])

In [7]:
np_0_m=np.zeros((3,5)) ##multidimensional array with Zeros
np_0_m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
##Generate random value 
np_ran=np.random.randint(10,50,5)
np_ran

array([18, 10, 36, 14, 14], dtype=int32)

In [16]:
##Generate random value multidimensional
np_mul=np.random.randint(30, size=(2,4))
np_mul

array([[21, 22,  6,  0],
       [21,  8, 16,  5]], dtype=int32)

In [8]:
##np_m_list
print(np_m_list.size)
print(np_m_list.shape)
np_m_list

9
(3, 3)


array([[ 1,  2,  3],
       [ 8,  9,  6],
       [11, 32, 90]])

In [7]:
#get the first row & column value
print(np_m_list[0,0])

1


In [9]:
np_m_list.item(1,2)

6

In [11]:
np.take(np_m_list,[0,3,6])

array([ 1,  8, 11])

In [12]:
print("Before: ",np_m_list)
np.put(np_m_list,[0,3,6],[21,17,33])
print(np_m_list)

Before:  [[ 1  2  3]
 [ 8  9  6]
 [11 32 90]]
[[21  2  3]
 [17  9  6]
 [33 32 90]]


In [13]:
np_m_list[:5:2]

array([[21,  2,  3],
       [33, 32, 90]])

In [16]:
##Get the second value from each row
np_m_list[:,1]

array([ 2,  9, 32])

In [17]:
##Getting veens value
even=np_m_list[np_m_list%2==0]
even

array([ 2,  6, 32, 90])

**Reshaping arrays**


1. Reshape the array to 1 by 9
2. Transpose 

In [33]:
np_m_list.resize((3,3))
print(np_m_list)
np_m_list.resize((1,9))
print(np_m_list)
np_m_list.resize((3,3))
np_m_list.transpose()
np_m_list

[[21  2  3]
 [17  9  6]
 [33 32 90]]
[[21  2  3 17  9  6 33 32 90]]


array([[21,  2,  3],
       [17,  9,  6],
       [33, 32, 90]])

In [34]:
np_m_list.swapaxes(0,1)
np_m_list
np_m_list.flatten()
np_m_list

array([[21,  2,  3],
       [17,  9,  6],
       [33, 32, 90]])

In [35]:
np_m_list.sort(axis=1)
print(np_m_list)

[[ 2  3 21]
 [ 6  9 17]
 [32 33 90]]


**Basic Maths  Numpy**
1. Addition
2. Subtraction
3. multiplication
4. Division
5. Min/Max

In [40]:
arr_1 = np.array([1, 2, 3, 6])
arr_2 = np.array([7, 9, 2, 8])
arr_1 + arr_2
arr_1 - arr_2
arr_1 * arr_2
arr_1 / arr_2

array([0.14285714, 0.22222222, 1.5       , 0.75      ])

In [42]:
arr3=np.random.randint(100, size=(4))
arr3

array([62, 15, 97, 48], dtype=int32)

In [56]:
arr4=np.random.randint(100, size=(4,4))
arr4
## Min

array([[91, 27, 17, 17],
       [10, 23, 35, 36],
       [16, 83,  0, 37],
       [76, 73, 33, 74]], dtype=int32)

In [57]:
arr4.min(axis=1)

array([17, 10,  0, 33], dtype=int32)

In [58]:
arr4.min(axis=0)

array([10, 23,  0, 17], dtype=int32)

In [44]:
arr4.sum()

np.int64(400)

In [45]:
arr4.sum(axis=0)

array([187,  14,  82, 117])

In [55]:
arr5=arr4=np.random.randint(100, size=(2,2))
print(arr5)
print("Sum R: ",arr5.sum(axis=1))
print("Sum C:",arr5.sum(axis=0))

[[64 43]
 [75 60]]
Sum R:  [107 135]
Sum C: [139 103]


In [59]:
arr_6 = np.array([[1, 2], [3, 6]])
arr_7 = np.array([[2,1],[6,9]])
print(f"arr_6\n{arr_6}")
print(f"arr_7\n{arr_7}")

arr_6
[[1 2]
 [3 6]]
arr_7
[[2 1]
 [6 9]]


In [61]:
np.power(arr_6,arr_7)

array([[       1,        2],
       [     729, 10077696]])

In [62]:
np.sqrt(arr_6)

array([[1.        , 1.41421356],
       [1.73205081, 2.44948974]])