In [12]:
##This will install numpy package in for this notebook.
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
##import here to use it
import numpy as np
##checking the version
print(np.__version__)

x=np.array([11,1,2,3])
print(x)
#check the data type
print(x.dtype)
nlist=[5,9,23,87]
x_np=np.array(nlist,dtype=np.int8)
print(x_np)
x_np.dtype

2.5.1
[11  1  2  3]
int64
[ 5  9 23 87]


dtype('int8')

In [12]:
## multidimesnional list
m_list=[[1,2,3],[8,9,6],[11,32,90]]
m_list

[[1, 2, 3], [8, 9, 6], [11, 32, 90]]

In [19]:
## multidimesnional numpy array
np_m_list=np.array(m_list)
#np_m_list=np.array(m_list, dtype=np.int8) //passing data type
print("Data type: ",np_m_list.dtype)
np_m_list

Data type:  int64


array([[ 1,  2,  3],
       [ 8,  9,  6],
       [11, 32, 90]])

In [23]:
np_int1=np.arange(1,10) #start & stop
np_int1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])